"""Build the browser question bank from the checked-in Markdown source."""

import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'source/Bank_Soal_DJPb_Paket_1-9_CASE_ANALITIS.md'
OUTPUT = ROOT / 'assets/questions.js'
# Editorial changes preserve answer meaning and order, so existing progress remains valid.
# Change this identifier when questions or answer positions change substantively.
PROGRESS_VERSION = 'case-analitis-4be2f51c00e6242a'


def plain(text):
    return text.replace('**', '').strip()


def parse_bank(text):
    packages = []
    for part in re.split(r'^## Paket ', text, flags=re.M)[1:]:
        heading, body = part.split('\n', 1)
        match = re.fullmatch(r'(\d+) — (.+)', heading.strip())
        if not match:
            raise ValueError(f'Invalid package heading: {heading}')
        package_id, title = int(match[1]), match[2]
        questions = []
        for block in re.split(r'^### Soal ', body, flags=re.M)[1:]:
            number, content = block.split('\n', 1)
            number = int(number.strip())
            label = f'Paket {package_id}, soal {number}'
            options = re.findall(r'^- \*\*([A-D])\.\*\* (.+)$', content, re.M)
            answer = re.search(r'^> ✅ \*\*Jawaban:\*\* \*\*([A-D])\. (.+)\*\*$', content, re.M)
            explanation = re.search(r'^> 💡 \*\*Pembahasan singkat:\*\* (.+(?:\n>[^\n]*)*)', content, re.M)
            prompt = content.split('- **A.**', 1)[0].strip()
            if [key for key, _ in options] != list('ABCD') or not answer or not explanation or not prompt:
                raise ValueError(f'{label}: incomplete question, options, answer, or explanation')
            answer_text = plain(answer[2])
            if plain(dict(options)[answer[1]]) != answer_text:
                raise ValueError(f'{label}: answer does not match its option')
            questions.append({
                'id': f'p{package_id}q{number}',
                'number': number,
                'question': plain(prompt),
                'options': [{'key': key, 'text': plain(value)} for key, value in options],
                'answer': answer[1],
                'answerText': answer_text,
                'explanation': plain(re.sub(r'\n> ?', '\n', explanation[1])),
            })
        if [q['number'] for q in questions] != list(range(1, 31)):
            raise ValueError(f'Paket {package_id}: expected questions 1–30')
        packages.append({'id': package_id, 'title': title, 'questions': questions})
    if [p['id'] for p in packages] != list(range(1, 10)):
        raise ValueError('Expected packages 1–9')
    revision = hashlib.sha256(json.dumps(packages, ensure_ascii=False, sort_keys=True).encode()).hexdigest()[:16]
    return {'version': f'case-analitis-{revision}', 'progressVersion': PROGRESS_VERSION,
            'source': SOURCE.name, 'packages': packages}


if __name__ == '__main__':
    bank = parse_bank(SOURCE.read_text(encoding='utf-8-sig'))
    OUTPUT.write_text('// Generated by scripts/build_questions.py; edit the Markdown source.\n'
                      + 'window.DJPB_QUESTION_BANK = ' + json.dumps(bank, ensure_ascii=False, indent=2) + ';\n',
                      encoding='utf-8')
    print(f"Built {len(bank['packages'])} packages / 270 questions ({bank['version']}).")
